<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUeuhc5f\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUeuhc5f/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUeuhc5f.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUeuhc5f\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUeuhc5f\appProdProjectContainer([
    'container.build_hash' => 'Ueuhc5f',
    'container.build_id' => '177a4b8e',
    'container.build_time' => 1582787009,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUeuhc5f');
