<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZp7uaxl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZp7uaxl/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZp7uaxl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZp7uaxl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZp7uaxl\appProdProjectContainer([
    'container.build_hash' => 'Zp7uaxl',
    'container.build_id' => 'e03a3179',
    'container.build_time' => 1582527087,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZp7uaxl');
