<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX0qqsmv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX0qqsmv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX0qqsmv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX0qqsmv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX0qqsmv\appDevDebugProjectContainer([
    'container.build_hash' => 'X0qqsmv',
    'container.build_id' => '3c4951be',
    'container.build_time' => 1582792549,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX0qqsmv');
