<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEaxbxl5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEaxbxl5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEaxbxl5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEaxbxl5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerEaxbxl5\appDevDebugProjectContainer([
    'container.build_hash' => 'Eaxbxl5',
    'container.build_id' => 'b0462866',
    'container.build_time' => 1582527441,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEaxbxl5');
